# Generated by Django 6.0.2 on 2026-02-23 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_url', models.CharField(blank=True, max_length=255, null=True)),
                ('voto_media', models.FloatField(default=0.0)),
                ('generos', models.ManyToManyField(related_name='filmes', to='core.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_favoritos', to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filme')),
            ],
            options={
                'unique_together': {('usuario', 'filme')},
            },
        ),
    ]
