# Generated by Django 6.0.2 on 2026-02-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_filme_tmdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='tmdb_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genero',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
