# Generated by Django 6.0.2 on 2026-02-24 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_filme_tmdb_id_alter_genero_tmdb_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='criado_em',
            new_name='data_adicionado',
        ),
        migrations.RenameField(
            model_name='filme',
            old_name='backdrop_url',
            new_name='poster_path',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='data_lancamento',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='generos',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='voto_media',
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmes', to='core.genero'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
