# Generated by Django 6.0.2 on 2026-02-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_criado_em_favorito_data_adicionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='duracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='idioma_original',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='filme',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='filme',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
