# Generated by Django 6.0.2 on 2026-02-27 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_avaliacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
